"""auto update

Revision ID: 28a6dcc8b5d2
Revises: d0bd1b3dc1b2
Create Date: 2026-03-13 18:25:43.160391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a6dcc8b5d2'
down_revision: Union[str, Sequence[str], None] = 'd0bd1b3dc1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rooms', sa.Column('current_round', sa.Integer(), nullable=True))
    op.add_column('room_players', sa.Column('total_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_players', 'total_score')
    op.drop_column('game_rooms', 'current_round')
    # ### end Alembic commands ###