"""auto update

Revision ID: d0bd1b3dc1b2
Revises: 
Create Date: 2026-03-13 17:34:29.576848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bd1b3dc1b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_rooms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_code', sa.String(), nullable=False),
    sa.Column('target_word', sa.String(), nullable=False),
    sa.Column('host_player_id', sa.String(), nullable=False),
    sa.Column('game_started', sa.Boolean(), nullable=True),
    sa.Column('winner_player_id', sa.String(), nullable=True),
    sa.Column('winner_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_rooms_id'), 'game_rooms', ['id'], unique=False)
    op.create_table('room_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('guesses', sa.Integer(), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=True),
    sa.Column('failed', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_players_id'), 'room_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_players_id'), table_name='room_players')
    op.drop_table('room_players')
    op.drop_index(op.f('ix_game_rooms_id'), table_name='game_rooms')
    op.drop_table('game_rooms')
    # ### end Alembic commands ###